import { Inter, Nerko_One } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const nerkoOne = Nerko_One({ subsets: ["latin"],weight: ["400"] });

export const metadata = {
  title: "UBAID PORTFOLIO",
  description: "Generated by Ubaid Raza",
  icons: {
    icon: '/fav.icon.jpg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nerkoOne.className}>{children}</body>
    </html>
  );
}
