import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {


  title: "Ukasha PORTFOLIO",
  description: "Generated by Ukasha Saifee",
  icon:['/fav.icon.jpg'],
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
